version: 2.1

filters-release: &filters-release
  tags:
    only: 
      - /^v.*/
  branches:
    ignore: /.*/

restore_go_cache: &restore_go_cache
  restore_cache:
    keys:
      - go-mod-{{ checksum "go.sum" }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
      - go-mod-{{ checksum "go.sum" }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}
      - go-mod-{{ checksum "go.sum" }}-{{ .Environment.CIRCLE_JOB }}-main

save_go_cache: &save_go_cache
  save_cache:
    when: always
    key: go-mod-{{ checksum "go.sum" }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
    paths:
      - /home/circleci/go/pkg/mod

commands:
  prepare-publish-artifacts:
    parameters:
      platform:
        type: string
        default: "linux-amd64"
      file_extension:
        type: string
        default: ""
    steps:
      - run: |
          cp build/bin/gqrl<< parameters.file_extension >> /tmp/gqrl-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>

          (cd /tmp && sha256sum gqrl-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >> > gqrl-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sha256)

          echo -n "$GPG_KEY" | base64 --decode | gpg --import
          gpg -o /tmp/gqrl-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sig --default-key 28580FDD99DA68203ABCE4205EA04E4E0FAC11B6 --sign --detach-sig /tmp/gqrl-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>

          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=theQRL repo=go-qrl tag=${CIRCLE_TAG} filename=/tmp/gqrl-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=theQRL repo=go-qrl tag=${CIRCLE_TAG} filename=/tmp/gqrl-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=theQRL repo=go-qrl tag=${CIRCLE_TAG} filename=/tmp/gqrl-${CIRCLE_TAG}-<< parameters.platform >><< parameters.file_extension >>.sig

jobs:
  publish-linux-amd64-gqrl-binary:
    docker:
      - image: cimg/go:1.25
    steps:
      - checkout
      - *restore_go_cache
      - run:
          command: go mod download
      - *save_go_cache
      - run: |
          go run build/ci.go install ./cmd/gqrl
      - prepare-publish-artifacts:
          platform: "linux-amd64"
  
  publish-linux-arm64-gqrl-binary:
    machine:
      image: ubuntu-2204:2024.11.1
    resource_class: arm.medium
    steps:
      - checkout
      - *restore_go_cache
      - run:
          command: go mod download
      - *save_go_cache
      - run: |
          go run build/ci.go install ./cmd/gqrl
      - prepare-publish-artifacts:
          platform: "linux-arm64"

  publish-darwin-amd64-gqrl-binary:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run: |
          # NOTE(rgeraldes24): currently relying on brew auto update to have the latest
          # versions of golang available but this can be achieved in other ways!
          brew install go@1.22
          echo 'export PATH="/usr/local/opt/go@1.22/bin:$PATH"' >> /Users/distiller/.bash_profile
          brew install coreutils
          brew install gpg
      - *restore_go_cache
      - run:
          command: go mod download
      - *save_go_cache
      - run: 
          command: go run build/ci.go install ./cmd/gqrl
      - prepare-publish-artifacts:
          platform: "darwin-amd64"

  build-and-deploy-docker-images:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Deploy Docker Images
          command: |
            go run build/ci.go dockerx -platform linux/amd64,linux/arm64 -hub qrledger/go-qrl -upload true

workflows:
  release:
    jobs:
      - publish-linux-amd64-gqrl-binary:
          filters:
            <<: *filters-release
      - publish-linux-arm64-gqrl-binary:
          filters:
            <<: *filters-release
      - publish-darwin-amd64-gqrl-binary:
          filters:
            <<: *filters-release
      - build-and-deploy-docker-images:
          filters:
            <<: *filters-release
